apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: fullstack
spec:
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30182
  selector:
    app: order-service
  type: NodePort