apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"db-pvc","namespace":"step-3"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"manual"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2025-11-05T10:24:47Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2025-11-05T17:44:52Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: db-pvc
  namespace: step-3
  resourceVersion: "68318"
  uid: 815a1931-0dd0-408d-b42c-d647b21e044f
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: db-pv
status:
  phase: Lost
