apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lab-k3s
spec:
  selector:
    app: backend      # doit correspondre au label de ton Deployment backend
  type: NodePort      # expose le service sur un port du node
  ports:
    - protocol: TCP
      port: 5000       # port interne du service
      targetPort: 5000 # port du container backend
      nodePort: 30080  # port sur le node pour y acc√©der depuis le navigateur
