apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: fullstack
spec:
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30181
  selector:
    app: book-service
  type: NodePort