apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: step-2
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy   # "mongouser" encodé en base64 # echo -n "mongouser" | base64
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29wYXNz   # "mongopass" encodé en base64 # echo -n "mongopass" | base64
